# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby "3.4.6"

gem "sinatra", "~> 2.2"
gem "sinatra-contrib", "~> 2.2"

gem "sqlite3"

gem "puma", "~> 5.6"
