# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby "3.4.6"

gem "sinatra", "~> 4.1"
gem "sinatra-contrib", "~> 4.1"

gem "sqlite3"

gem "rackup"
gem "puma", "~> 7.0"
